export default [
	["majorStreets", "Major Streets"],
	["diagonals", "Diagonals"],
	["neighborhoods", "Neighborhoods"],
	["landmarks", "Chicago Landmarks"],
	["parks", "Parks"],
	["pedway", "Pedway"],
	["expressways", "Expressways"],
	["numberedStreets", "Numbered Streets"],
	["alphabeticalAvenues", "Alphabetical Avenues"],
	["floraStreets", "Flora-themed Streets"],
	["generalStreets", "Streets named after Generals"],
	["greatLakeStreets", "Streets named after Great Lakes"],
	["presidentialStreets", "Streets named after Presidents"],
	["ranchStreets", "RANCH Triangle"],
	["multilevelStreets", "Multilevel Streets"],
	["kStreets", "Mile of Streets that start with 'K'"],
	["lStreets", "Mile of Streets that start with 'L"],
	["mStreets", "Mile of Streets that start with 'M'"],
	["nStreets", "Mile of Streets that start with 'N'"],
	["oStreets", "Mile of Streets that start with 'O'"],
	["pStreets", "Mile of Streets that start with 'P'"],
];
