export default [
	["alphabeticalAvenues", "Alphabetical Avenues"],
	["diagonals", "Diagonals"],
	["expressways", "Expressways"],
	["floraStreets", "Flora-themed Streets"],
	["generalStreets", "Streets named after Generals"],
	["greatLakeStreets", "Streets named after Great Lakes"],
	["kStreets", "Streets that start with 'K'"],
	["landmarks", "Chicago Landmarks"],
	["lStreets", "Streets that start with 'L"],
	["majorStreets", "Major Streets"],
	["mStreets", "Streets that start with 'M'"],
	["multilevelStreets", "Multilevel Streets"],
	["neighborhoods", "Neighborhoods"],
	["nStreets", "Streets that start with 'N'"],
	["numberedStreets", "Numbered Streets"],
	["oStreets", "Streets that start with 'O'"],
	["parks", "Parks"],
	["pedway", "Pedway"],
	["presidentialStreets", "Streets named after Presidents"],
	["pStreets", "Streets that start with 'P'"],
	["ranchStreets", "RANCH Triangle"],
];
